import {FoodCategory, Restaraunt} from './TypeScript';

const FOOD1 = require('../assets/images/foods/1.png');
const FOOD2 = require('../assets/images/foods/2.png');
const FOOD3 = require('../assets/images/foods/3.png');
const FOOD4 = require('../assets/images/foods/4.png');
const FOOD5 = require('../assets/images/foods/5.png');
const FOOD6 = require('../assets/images/foods/6.png');
const FOOD7 = require('../assets/images/foods/7.png');
const FOOD8 = require('../assets/images/foods/8.png');
const FOOD9 = require('../assets/images/foods/9.png');
const FOOD10 = require('../assets/images/foods/10.png');
const FOOD11 = require('../assets/images/foods/11.png');
const FOOD12 = require('../assets/images/foods/12.png');

export const categories: FoodCategory[] = [
  {
    _id: '0',
    name: 'food',
  },
  {
    _id: '1',
    name: 'pizza',
  },
  {
    _id: '2',
    name: 'pasta',
  },
  {
    _id: '3',
    name: 'meat',
  },
  {
    _id: '4',
    name: 'fish',
  },
  {
    _id: '5',
    name: 'Burger',
  },
  {
    _id: '6',
    name: 'chicken',
  },
  {
    _id: '7',
    name: 'salad',
  },
];

export const restaraunts: Restaraunt[] = [
  {
    _id: '0',
    name: 'torta loca',
    category: 'mexican restarunt',
    logo: 'https://i.pinimg.com/564x/03/b6/45/03b645a468a8691b1381fd3c7656c8e5.jpg',
    address: 'derech menachem begin 144 telaviv',
    tel: '035142722',
    position: {lag: '10', lat: '12'},
    rating: 4,
    distance: 5,
    isOpen: true,
    verified: true,
    slogan: 'mexican restarunt delivers to you',
    workHours: {from: '9', to: '12'},
    managerName: 'avare mind',
    chef: 'solor batch',
    visitThisMonth: 414,
    reviews: ['best restaraunt'],
    story:
      'Saepe soluta laborum dolores, repellat rerum hic numquam mollitia possimus inventore dignissimos, temporibus laboriosam alias, iste voluptatum sunt consequuntur exercitationem dolorum aliquam.',
    images: [
      'https://i.pinimg.com/564x/d7/34/5e/d7345ed26dc802630e40e01c5f36cc14.jpg',
      'https://i.pinimg.com/564x/1c/48/56/1c48562fe15c9e5dd4206e5a667ebe7a.jpg',
      'https://i.pinimg.com/564x/7c/ae/bf/7caebf45e49a355202b45c903e407538.jpg',
    ],
    tags: ['Chicken', 'Bowls'],
    socials: [],
    website: '',
    menu: [
      {
        _id: '0',
        name: 'Chicken and Cauliflower “Rice” Bowls',
        price: '24',
        images: [FOOD7],
        category: categories[0],
        calories: 80,
        weight: 400,
        compositions: [
          'Meat',
          'Avocado',
          'Garlic cloves',
          'tsp Garlic powder',
          'Green onions',
        ],
        desc: 'Gluten freeChicken and Cauliflower “Rice” Bowls',
        rating: 4,
        createdAt: '2021/12/14',
      },
      {
        _id: '1',
        name: 'Chicken Fajita Kebabs - Cooking Classy',
        price: '32',
        images: [FOOD1, FOOD4],
        createdAt: '2021/12/14',
        category: categories[0],
        compositions: [],
        desc: "Chicken pieces are soaked in a bright, citrusy, well season marinade then threaded onto skewers along with fresh bell peppers and onions. Then they're grilled over hot flames to give them that fire…",
        rating: 4,
        calories: 80,
        weight: 400,
      },
      {
        _id: '2',
        name: 'chees chilly fried',
        price: '29',
        images: [FOOD6],
        createdAt: '2021/12/14',
        category: categories[0],
        compositions: [],
        desc: "citrusy, well season marinade then threaded onto skewers along with fresh bell peppers and onions. Then they're grilled over hot flames to give them that fire…",
        rating: 4,
        calories: 80,
        weight: 400,
      },
    ],
  },
  {
    _id: '1',
    name: 'saone rhone',
    category: 'fast food restarunt',
    logo: 'https://i.pinimg.com/564x/df/de/e5/dfdee51eec0f3d4d6840cf56567e4166.jpg',
    address: 'Yehuda Halevi 44 Tel Aviv',
    tel: '035145722',
    position: {lag: '10', lat: '11'},
    rating: 4,
    distance: 5,
    isOpen: true,
    verified: true,
    slogan: '',
    workHours: {from: '9', to: '12'},
    managerName: 'avare mind',
    chef: 'solor batch',

    visitThisMonth: 414,
    reviews: [],
    images: [
      'https://i.pinimg.com/564x/a7/59/67/a75967c6d7097c0e2960a42e2dd5afcd.jpg',
    ],
    tags: [],
    socials: [],
    story:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe soluta laborum dolores, repellat rerum hic numquam mollitia possimus inventore dignissimos, temporibus laboriosam alias, iste voluptatum sunt consequuntur exercitationem dolorum aliquam.',
    website: '',
    menu: [
      {
        _id: '0',
        name: 'Flat lay with italian pizza containing pizza, flat, and lay',
        price: '12',
        images: [FOOD2],
        createdAt: '2021/12/14',
        category: categories[0],
        compositions: [],
        desc: 'Share feedback, ask a question or give a high five',
        rating: 4,
        calories: 80,
        weight: 400,
      },
      {
        _id: '1',
        name: 'Pizza Background Material',
        price: '10',
        images: [FOOD3],
        createdAt: '2021/12/14',
        category: categories[0],
        compositions: [],
        desc: 'More than 3 million PNG and graphics resource at Pngtree. Find the best inspiration you need for your project.',
        rating: 4,
        calories: 80,
        weight: 400,
      },
    ],
  },
  {
    _id: '2',
    name: 'under the tree',
    category: 'cafe',
    logo: 'https://i.pinimg.com/564x/f8/f1/a3/f8f1a30b4107f679e62f76aa483b32db.jpg',
    address: 'Ben Yehuda Street 202 Tel Aviv',
    tel: '035142722',
    position: {lag: '10', lat: '12'},
    rating: 4,
    distance: 5,
    isOpen: true,
    verified: true,
    slogan: 'We look in depth to see how coffee can affect out health',
    workHours: {from: '9', to: '12'},
    managerName: 'avare mind',
    chef: 'solor batch',

    visitThisMonth: 414,
    story: '',
    reviews: [],
    images: [
      'https://i.pinimg.com/564x/56/8e/d4/568ed475b58947ad8e10f80f6c83b1c9.jpg',
      'https://i.pinimg.com/564x/ca/dc/8c/cadc8c014cf037cdb9f97059fbfa8380.jpg',
    ],
    tags: [],
    socials: [],
    website: '',
    menu: [
      {
        _id: '0',
        name: 'torky caffee',
        price: '5',
        images: [FOOD10, FOOD12],
        createdAt: '2021/12/14',
        category: categories[0],
        compositions: [],
        desc: '',
        rating: 4,
        calories: 80,
        weight: 400,
      },
      {
        _id: '1',
        name: 'bitter caffee',
        price: '6',
        images: [FOOD11],
        createdAt: '2021/12/14',
        category: categories[0],
        compositions: [],
        desc: '',
        rating: 4,
        calories: 80,
        weight: 400,
      },
    ],
  },
  {
    _id: '3',
    name: 'lila',
    category: 'pizza',
    logo: 'https://i.pinimg.com/564x/80/44/48/8044480876233e8fc8d20a601482a56b.jpg',
    address: 'Merkhavya Street 4 Tel Aviv',
    tel: '035142722',
    position: {lag: '10', lat: '12'},
    rating: 4,
    distance: 5,
    isOpen: true,
    verified: true,
    slogan: '',
    workHours: {from: '9', to: '12'},
    managerName: 'avare mind',
    chef: 'solor batch',
    visitThisMonth: 414,
    story:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe soluta laborum dolores, repellat rerum hic numquam mollitia possimus inventore dignissimos, temporibus laboriosam alias, iste voluptatum sunt consequuntur exercitationem dolorum aliquam.',
    reviews: [],
    images: [
      'https://i.pinimg.com/564x/08/6a/e9/086ae9bd5dde14da91fa477706420a52.jpg',
    ],
    tags: [],
    socials: [],
    website: '',
    menu: [
      {
        _id: '0',
        name: 'Cast Iron Pizza',
        price: '10',
        images: [FOOD9],
        createdAt: '2021/12/14',
        category: categories[0],
        compositions: ['olives', 'Meat'],
        desc: 'This cast iron pizza with spicy Italian sausage is prepared with an easy, no-knead pizza dough and is a scrumptious offering for pizza night!',
        rating: 4,
        calories: 80,
        weight: 400,
      },
      {
        _id: '0',
        name: 'BBQ Chicken Pizza',
        price: '8',
        images: [FOOD8, FOOD5],
        createdAt: '2021/12/14',
        category: categories[0],
        compositions: ['Chicken Meat', ' fresh leaves'],
        desc: "Cheesy BBQ Chicken Pizza recipe - Slathered with BBQ sauce and sprinkled with tons of mozzarella and gouda, you'll want to make this pizza again and again!",
        rating: 4,
        calories: 80,
        weight: 400,
      },
    ],
  },
];
